version: '3.8'

services:
  market-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market-analysis-system
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - TZ=Asia/Taipei
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8089
      - WEBHOOK_URL=${WEBHOOK_URL:-https://beloved-swine-sensibly.ngrok-free.app/webhook-test/ef5ac185-f41a-4a2d-9a78-33d329184c2}
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT:-30}
      - API_KEY=${API_KEY:-}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./backups:/app/backups
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8089/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - market-network

  ngrok-market:
    image: ngrok/ngrok:3-alpine
    container_name: ngrok-market-analysis
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-2zzNP5hnqCVT1EkLieXmLyNEUnX_7RqY7RwqEPheVpbbeRRX6}
    ports:
      - "4041:4040"
    command: ["http", "market-analysis:8089", "--log=stdout", "--region=ap"]
    depends_on:
      market-analysis:
        condition: service_healthy
    networks:
      - market-network

networks:
  market-network:
    driver: bridge