# ================================
# 市場分析報告系統 - 修正版 Docker Compose 配置
# Market Analysis Report System - Fixed Docker Compose Configuration
# ================================

services:
  # 主要應用服務
  market-analysis:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-}
    container_name: market-analysis-app
    ports:
      - "${SERVER_PORT:-8089}:8089"
    environment:
      # 基本配置
      ENVIRONMENT: ${ENVIRONMENT:-production}
      DEBUG: ${DEBUG:-false}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

      # 伺服器配置
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8089

      # Webhook 配置
      WEBHOOK_URL: ${WEBHOOK_URL:-https://beloved-swine-sensibly.ngrok-free.app/webhook-test/ef5ac185-f41a-4a2d-9a78-33d329184c2}
      WEBHOOK_TIMEOUT: 30

      # 時區設定
      TZ: Asia/Taipei
    volumes:
      # 資料持久化
      - ./logs:/app/logs
      - ./data:/app/data
      - ./backups:/app/backups
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis 快取服務（可選）
  redis:
    image: redis:7-alpine
    container_name: market-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - redis

# 資料卷
volumes:
  redis_data:
    driver: local